server:
  port: 9003

spring:
  application:
    name: service-oss


aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      key-id: LTAI5t5th66iKzejiiviWFph
      key-secret: zoVljDu4PmK0ykjh8ttloRg5EbZI9C
      bucket-name: dd-20221107
